function [Pointsx, Pointsy, Vid] = analyzeJumpVid(vidfile,jumptime,frdur,cnt)
% function [Pointsx,Pointsy, FR] = analyzeJumpVid(vidfile,jumptime,frdur)
% Read in Eye Tracking Video
TempVid = VideoReader(vidfile);
frame=1; k=1;
FR = round(TempVid.FrameRate);
TempVid.CurrentTime = jumptime/FR; %subtract 5 seconds from actual jump time so you get bobs
CT =TempVid.CurrentTime;
frdur=frdur*FR;
for frame = 1: frdur
        Vid(:,:,k) = rgb2gray(readFrame(TempVid));
        if mod(frame,100)==0
            fprintf('frame = %d\n',frame)
        end
        k=k+1;
%         end
%         frame=frame+1;

end

% Load the .csv file generated by DLC
csvf = dir([vidfile(1:end-4) '*.csv']);
Pointsxy = csvread(csvf.name,3,0);
vidsize=round(FR*CT:FR*CT+frdur-1); % size(Vid,3); %1:1000;
try
    Pointsx = Pointsxy(vidsize,[2:3:end]); Pointsy = Pointsxy(vidsize,[3:3:end]);
catch
    Pointsx = Pointsxy(vidsize(1):size(Pointsxy,1),[2:3:end]); Pointsy = Pointsxy(vidsize(1):size(Pointsxy,1),[3:3:end]);
end
% LH =  Pointsxy(vidsize,[4:3:end]);

% fprintf('Done Reading in Video \n');


%% Plot Ellipse Fits on Image
% figure;
% axis tight manual
% ax = gca;
% ax.NextPlot = 'replaceChildren';
% % axis([1 size(Vid,1) 1 size(Vid,2)] )
% % EllipseParams = zeros(size(Vid,3),6);
% 
% for v=1:size(Vid,3)
%     imagesc(Vid(:,:,v)); colormap gray; axis equal off; hold on;
%     
%     scatter(Pointsx(v,:),Pointsy(v,:),100,'.r'); % Uncomment if you wish plot points
% %     if ~any((Pointsx(v,:)<10 | Pointsy(v,:)<10)) % check points
% %         xp = Pointsx(v,:); yp =Pointsx(v,:);
% %         e_t = fit_ellipse(xp(~isnan(xp))',yp(~isnan(yp))',ax);
% %     end
%     hold off;
%     title(sprintf('Frame = %d',v));
%     drawnow limitrate;
% %     pause
% end

%% Make movie with points
figure;
axis tight manual
ax = gca;
ax.NextPlot = 'replaceChildren';
vname = sprintf('%s_%d.mp4',vidfile(1:end-4),cnt)
vidfile = VideoWriter(vname,'MPEG-4');
% vidfile = VideoWriter('Jump1b.avi');
vidfile.FrameRate = FR/4;
open(vidfile);
for  v=1:3:size(Vid,3)
    subplot(2,1,1)
    plot(-Pointsy(:,1),'k')
    hold on
    plot([v v],[0 -500],'r-')
    hold off
    subplot(2,1,2)
    imagesc(Vid(:,:,v)); colormap gray; hold on; axis equal off;
    scatter(Pointsx(v,:),Pointsy(v,:),100,'.r'); hold off; % Uncomment if to plot DLC points too
%     if ~any((Pointsx(v,:)<10 | Pointsy(v,:)<10)) % check points
%         e_t = fit_ellipse(Pointsx(v,:),Pointsy(v,:),ax);
%     end
%     title(sprintf('Frame = %d',v));
    drawnow% limitrate;
    F(v) = getframe(gcf); 
    writeVideo(vidfile,F(v));
%     fprintf('Frame = %d \n',v);
end
% subplot(2,1,1)
% title('select before and after bob')
% [x,y] = ginput(2);x=round(x);y=round(y);
% trace = [Pointsy(x(1):x(2));Pointsx(x(1):x(2))];
close
close(vidfile)

%% make plot
% figure
% hold on
% % plot(Pointsx(:,1))
% plot(Pointsy(:,1)/mean(Pointsy(:,1)),'k')
% axis([50 153 0.84 1.15])
% axis off
%% making figure for K99 (Phil)

% Pointsx(154,1) = 1151;
% Pointsx(154,2) = 1231;
% Pointsy(154,1) = 223;
% Pointsy(154,2) = 219;

% keyboard
%% make figures for K99
% figure;plot(Pointsy(:,1),'k')
% framen = [150,164,169,178,183,195];
% for i = 1:length(framen)
%     h=figure;
%     imshow(Vid(:,:,framen(i)))
%     hold on
%     scatter(Pointsx(framen(i),1:2),Pointsy(framen(i),1:2),500,'r.')
%     saveas(h,sprintf('frame%d.png',framen(i)))
%     close
% end
% figure;plot(Pointsy(145:200,1),'k')